import Head from 'next/head'
import styles from 'styles/Home.module.css'
import { Fragment, useContext, useEffect } from "react"
import { BooksContext } from "context-api/BooksContext"
import Link from 'next/link'
import Container from "@material-ui/core/Container"
import "tachyons"
import Divider from "@material-ui/core/Divider"
import Image from "next/image"
import InfoOutlinedIcon from '@material-ui/icons/InfoOutlined'

const Home = ({ booksData = []}) => {
  const {books, setBooks} = useContext(BooksContext)

  useEffect(() => {
    setBooks(booksData.books)
  }, [booksData])

  return (
    <Container maxWidth='md'>
      <Head>
        <title>Reading List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 className='tc'>Reading List</h1>
      </header>

      <main className={styles.main}>
        <div className='h-100'>
          <ul className='list pl0'>
            {books.map(({id, title, author, cover}, index) => (
              <Fragment key={id}>
                <li className='mv3'>
                  <div className='flex'>
                    <div className='relative mr3 h-100' style={{ width: 50, height: 50 }}>
                      <Image alt={title} src={cover} layout="fill" objectFit="cover" />
                    </div>
                    <section>
                      <p className='mt0'>{title}</p>
                      <p>{author}</p>
                      <Link href={`/more-info/${id}`}>
                        <a className='underline-hover flex items-center'>
                          <InfoOutlinedIcon /> <p className='ml2 mv0'>More Info</p>
                        </a>
                      </Link>
                    </section>
                  </div>
                </li>
                {index !== books.length - 1 && <Divider />}
              </Fragment>
            ))}
          </ul>
        </div>
      </main>
    </Container>
  )
}

export async function getStaticProps(context) {
  const BOOKS_URL = 'https://hokodo-frontend-interview.netlify.com/data.json'
  const booksData = await fetch(BOOKS_URL).then(response => response.json())

  return { props: { booksData } }
}


export default Home